-- Generated from generator/demo_specs/aws-vietnam-electronics-capacity.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-vietnam-electronics-capacity
-- This is the schema that is actually deployed for VIETNAM_ELECTRONICS_CAPACITY.

-- Alerts fire on the bottom tail of Factory Utilization
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_FACTORY_UTILIZATION) AS T
  FROM RAW.PRODUCTION_RUNS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_FACTORY_UTILIZATION <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_FACTORY_UTILIZATION), 2) AS AVG_FACTORY_UTILIZATION,
  ROUND(AVG(f.KPI_YIELD_RATE), 2) AS AVG_YIELD_RATE,
  ROUND(AVG(f.KPI_CYCLE_TIME), 2) AS AVG_CYCLE_TIME,
  ROUND(AVG(f.KPI_OEE), 2) AS AVG_OEE
FROM RAW.PRODUCTION_RUNS f
JOIN RAW.PRODUCTION_LINES e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_FACTORY_UTILIZATION), 2) AS AVG_FACTORY_UTILIZATION,
  ROUND(AVG(f.KPI_YIELD_RATE), 2) AS AVG_YIELD_RATE,
  ROUND(AVG(f.KPI_CYCLE_TIME), 2) AS AVG_CYCLE_TIME,
  ROUND(AVG(f.KPI_OEE), 2) AS AVG_OEE
FROM RAW.PRODUCTION_RUNS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_FACTORY_UTILIZATION) AS KPI_FACTORY_UTILIZATION, AVG(KPI_YIELD_RATE) AS KPI_YIELD_RATE, AVG(KPI_CYCLE_TIME) AS KPI_CYCLE_TIME, AVG(KPI_OEE) AS KPI_OEE FROM RAW.PRODUCTION_RUNS),
     en AS (SELECT SUM(KPI_OUTPUT_MTD) AS KPI_OUTPUT_MTD, SUM(KPI_LINES_ACTIVE) AS KPI_LINES_ACTIVE FROM RAW.PRODUCTION_LINES)
  SELECT 1 AS SORT_ORDER, 'Factory Utilization' AS TITLE, KPI_FACTORY_UTILIZATION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_FACTORY_UTILIZATION)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Output (MTD)' AS TITLE, KPI_OUTPUT_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_OUTPUT_MTD) / 1000000), 1) AS DECIMAL(38,1))) || 'M' || ' ' || 'units' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Yield Rate' AS TITLE, KPI_YIELD_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_YIELD_RATE), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Lines Active' AS TITLE, KPI_LINES_ACTIVE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_LINES_ACTIVE)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Cycle Time' AS TITLE, KPI_CYCLE_TIME AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CYCLE_TIME), 1) AS DECIMAL(38,1))) || 's' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'OEE' AS TITLE, KPI_OEE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_OEE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
