-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Production Capacity Planning
-- ============================================================================
USE DATABASE ELECTRONICS_CAPACITY;
USE SCHEMA ML;

-- ML.FORECAST: ELECTRONICS_CAPACITY_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.ELECTRONICS_CAPACITY_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.FORECAST_INPUT'),
  SERIES_COLNAME => 'ENTITY_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.ELECTRONICS_CAPACITY_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.ELECTRONICS_CAPACITY_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: ELECTRONICS_CAPACITY_ANOMALY
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.ELECTRONICS_CAPACITY_ANOMALY(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.TREND_ANALYTICS'),
  SERIES_COLNAME => 'ENTITY_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.ELECTRONICS_CAPACITY_ANOMALY_RESULTS AS
SELECT * FROM TABLE(ML.ELECTRONICS_CAPACITY_ANOMALY!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.TREND_ANALYTICS'), SERIES_COLNAME => 'ENTITY_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

